### PR TITLE
Update nav drawer styling

### PR DESCRIPTION
**Pull request by gino-m**
Towards #1567 

image

### CODE REVIEW

**Comment by gino-m** [comment]
@shobhitagarwal1612 PTAL?

**Review by shobhitagarwal1612 — APPROVED** [review]
✨

**Comment by shobhitagarwal1612** [comment]
```

com.google.android.ground.ui.home.NavigationDrawerItemClickTest > clickDrawerMenuItem[Change survey] FAILED
    androidx.test.espresso.NoMatchingViewException at HomeScreenFragmentTest.kt:170

com.google.android.ground.ui.home.NavigationDrawerItemClickTest > clickDrawerMenuItem[Sync status] FAILED
    androidx.test.espresso.NoMatchingViewException at HomeScreenFragmentTest.kt:170

383 tests completed, 2 failed
```

**Comment by gino-m** [comment]
Tweaked styling:
image

**Comment by shobhitagarwal1612** [comment]
Lint is failing due to unused styles.

**Pull request merged**
