### PR TITLE
Fixed Survey Title max lines to 3 in Nav Drawer

### LINKED ISSUE #2444: [Nav drawer] Survey title truncated at one line
Should be truncated only after 2-3 lines

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2444 

### Before 
Screenshot 2024-08-06 at 8 55 30 AM

### After 
Screenshot 2024-08-06 at 8 55 59 AM
Screenshot 2024-08-06 at 8 57 15 AM

@shobhitagarwal1612  @sufyanAbbasi  PTAL?

### CODE REVIEW

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
Can you please check it the build is passing locally or not?

**Comment by anandwana001** [comment]
Yes, it is passing locally

**Pull request merged**
