### PR TITLE
AsyncSingletonProvider: double-checked locking pattern

### LINKED ISSUE #2079: Refactor AsyncSingletonProvider to use double-checked locking.
- Ref: https://en.wikipedia.org/wiki/Double-checked_locking

### PR DESCRIPTION
**Pull request by hoc081098**
Will close #2079 
- [x] refactor AsyncSingletonProvider: use double-checked locking pattern

### CODE REVIEW

**Comment by gino-m** [comment]
Thanks @hoc081098! 
/gcbrun

**Comment by hoc081098** [comment]
@gino-m, it looks like the code does not conform the expected format.
Could you please show me the log 😇?

**Comment by gino-m** [comment]
> @gino-m, it looks like the code does not conform the expected format. Could you please show me the log 😇?

Sure! It appears to be a formatting issue:

> Execution failed for task ':workspace:ground:ktfmtCheckMain'.
> [ktfmt] Found 1 files that are not properly formatted:
  /workspace/ground/src/main/java/com/google/android/ground/util/AsyncSingletonProvider.kt

Can you try running `gradle ktfmtFormat`? There are a few edge cases where Android Studio ktfmt plugin doesn't apply the same rules as the Gradle ktfmt plugin.

**Comment by hoc081098** [comment]
@gino-m I have formatted code 🙏

**Review by gino-m — APPROVED** [review]
LGTM. Thanks for the fix!

**Pull request merged**
