### PR TITLE
[Code health] Document ActivityStreams

### PR DESCRIPTION
**Pull request by gino-m**
Work towards #699. 

@shobhitagarwal1612 PTAL?

### CODE REVIEW

**Review by shobhitagarwal1612 — APPROVED** [review]

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by gino-m** [comment]
@shobhitagarwal1612 Fixed lint checks. PTAL?

**Comment by shobhitagarwal1612** [comment]
Thanks Gino! Could you also resolve the conflicts?

**Comment by gino-m** [comment]
@shobhitagarwal1612 Could you kindly restamp? Thank you!

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by gino-m** [comment]
Thanks, @shobhitagarwal1612 !

**Pull request merged**
