### PR TITLE
[Code health] Replace Optional with Kotlin nullable (?)

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes https://github.com/google/ground-android/issues/1735

Replace usages of Optional<*> with kotlin nullable wherever possible. This doesn't remove all occurences of it since RxJava code still relies on it (null value throws an error).

@JSunde @gino-m  PTAL?

### CODE REVIEW

**Review by gino-m — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
@gino-m This is now ready for a review. I have made minor adjustments where Optional could be replaced with a non-nullable value. Please review commit-by-commit for better context.

**Review by JSunde — APPROVED** [review]

**Pull request merged**
