### PR TITLE
Loi Card and Suggest Loi Card UX Tweaks

### PR DESCRIPTION
**Pull request by JSunde**
Updates to cards to bring in line with latest mocks.

image
image

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
QQ: In the above screenshot, the suggest LOI card isn't highlighted. Is that intentional?

**Comment by JSunde** [comment]
> QQ: In the above screenshot, the Suggest LOI card isn't highlighted. Is that intentional?

Not entirely, it just hasn't been implemented yet. I believe the LOI cards are focused based on the active Location of Interest, which won't work for the Suggest LOI cards, so we'll have to manage the focused state differently for those.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
