### PR TITLE
Cleanup and reorganise data collection package

### LINKED ISSUE #1606: [Code health] Reorganise data collection package
Create a sub-package `tasks` under `datacollection`. For each of the type, create sub-packages to contain related classes.

Also cleanup any obsolete classes.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1606

(Please review commit-by-commit since the diff is large)

Things done in this PR:
 * Cleanup logic of adding tasks to EditSubmissionFragment. Since all task types are now implemented
 * Removed remaining layouts of previous tasks
 * Package classes under datacollection based on task type

Changes verified by running the app locally.

@JSunde @scolsen   PTAL?

### CODE REVIEW

**Comment by scolsen** [comment]
Nice work on this @shobhitagarwal1612! LGTM. Want to check it out locally, but assuming it all works there looks good to go.

**Review by JSunde — APPROVED** [review]

**Pull request merged**
