### PR TITLE
Upgrade versioner plugin

### LINKED ISSUE #2594: Clean builds are currently broken due to missing gitversioner plugin in Maven Central

### PR DESCRIPTION
**Pull request by gino-m**
..to a version which is still available in Maven Central.

Fixes #2594

### CODE REVIEW

**Comment by sufyanAbbasi** [comment]
Looks like there's still an issue with the build, that version doesn't seem to have been found either:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.pascalwelsch.gitversioner:gitversioner:0.6.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/pascalwelsch/gitversioner/gitversioner/0.6.3/gitversioner-0.6.3.pom
       - file:/root/.m2/repository/com/pascalwelsch/gitversioner/gitversioner/0.6.3/gitversioner-0.6.3.pom
       - https://maven.google.com/com/pascalwelsch/gitversioner/gitversioner/0.6.3/gitversioner-0.6.3.pom
       - https://plugins.gradle.org/m2/com/pascalwelsch/gitversioner/gitversioner/0.6.3/gitversioner-0.6.3.pom
       - https://repo.maven.apache.org/maven2/com/pascalwelsch/gitversioner/gitversioner/0.6.3/gitversioner-0.6.3.pom
     Required by:
         project :
```

**Comment by gino-m** [comment]
Yeah, I think the group ID has changed to `de.sharpmind` as well. Trying that now.

**Comment by gino-m** [comment]
Working now!

**Review by sufyanAbbasi — APPROVED** [review]
Thank you!

**Pull request merged**
