### PR TITLE
Run instrumentation tests only for push to master

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Changes made:
 1. Building instrumentation apk in "assemble_debug" step
 2. Running instrumentation tests in firebase test lab

@gino-m  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
This reduced the overall build time by ~2 mins for non-master pushes.

**Comment by shobhitagarwal1612** [comment]
Once this is merged, we can update the "comment control" settings under for "pull-request-to-ground-android" trigger to auto-trigger the build on every push.

image

**Review by gino-m — APPROVED** [review]
🤖👏!

**Comment by shobhitagarwal1612** [comment]
Comment control setting updated to "Not required".

**Pull request merged**
