### PR TITLE
Add values-fr folder with French translation of app

### PR DESCRIPTION
**Pull request by jo-spek**

### CODE REVIEW

**Review by sufyanAbbasi — APPROVED** [review]
Thank you so much!

**Comment by jo-spek** [comment]
I'm a bit confused here. Is this going forward now? Checks have failed because it's missing approval only, or is there another problem?

**Comment by gino-m** [comment]
Thanks @jo-spek ! In order to submit code to this repo you'll need to first accept the Google CLA at https://cla.developers.google.com/clas. 

Also, the checks are failing due to "Invalid unicode escape sequence in string" on several of the strings. Pasting the actual errors below.

Once those are resolved we should be able to approve and merge.


```
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:179:2: Failed to flatten XML for resource 'about_ground' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:179:2: string/about_ground does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:167:2: Failed to flatten XML for resource 'add_polygon_instructions' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:167:2: string/add_polygon_instructions does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:64:2: Failed to flatten XML for resource 'admin_request_access' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:64:2: string/admin_request_access does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:63:2: Failed to flatten XML for resource 'agree_checkbox' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:63:2: string/agree_checkbox does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/build/intermediates/incremental/localDebug/mergeLocalDebugResources/merged.dir/values-fr/values-fr.xml:64:46: Failed to flatten XML for resource 'camera_permissions_needed' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:[105](https://github.com/google/ground-android/actions/runs/11145054266/job/30973732464?pr=2770#step:5:106):2: string/camera_permissions_needed does not contain a valid string resource.
/home/runner/.gradle/caches/transforms-4/ebdaba96fc7f4b79a8c59e9a04d73490/transformed/jetified-ui-release/res/values-fr/values-fr.xml:2:4: Failed to flatten XML for resource 'close_app' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/.gradle/caches/transforms-4/ebdaba96fc7f4b79a8c59e9a04d73490/transformed/jetified-ui-release/res/values-fr/values-fr.xml:2:4: string/close_app does not contain a valid string resource.
/home/runner/.gradle/caches/transforms-4/1ed90711cc659b15448830118659bdc9/transformed/jetified-play-services-base-18.5.0/res/values-fr/values.xml:4:0: Failed to flatten XML for resource 'collect_data_viewer_error' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/.gradle/caches/transforms-4/1ed90711cc659b15448830118659bdc9/transformed/jetified-play-services-base-18.5.0/res/values-fr/values.xml:4:0: string/collect_data_viewer_error does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:182:2: Failed to flatten XML for resource 'data_sharing_private_message' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:182:2: string/data_sharing_private_message does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:186:2: Failed to flatten XML for resource 'data_sharing_public_message' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:186:2: string/data_sharing_public_message does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:85:2: Failed to flatten XML for resource 'drop_a_pin_tooltip_text' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:85:2: string/drop_a_pin_tooltip_text does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/build/intermediates/incremental/localDebug/mergeLocalDebugResources/merged.dir/values-fr/values-fr.xml:131:46: Failed to flatten XML for resource 'google_api_install_failed' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:174:2: string/google_api_install_failed does not contain a valid string resource.
/home/runner/.gradle/caches/transforms-4/a3168e7aa7fbcf54a144d073de929f3b/transformed/material-1.12.0/res/values-fr/values-fr.xml:18:4: Failed to flatten XML for resource 'invalid_data_sharing_terms' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/.gradle/caches/transforms-4/a3168e7aa7fbcf54a144d073de929f3b/transformed/material-1.12.0/res/values-fr/values-fr.xml:18:4: string/invalid_data_sharing_terms does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:149:2: Failed to flatten XML for resource 'location_updates_unknown_error' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:149:2: string/location_updates_unknown_error does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:87:2: Failed to flatten XML for resource 'network_error_when_signing_in' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:87:2: string/network_error_when_signing_in does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:32:2: Failed to flatten XML for resource 'no_basemaps_downloaded' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:32:2: string/no_basemaps_downloaded does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/build/intermediates/incremental/localDebug/mergeLocalDebugResources/merged.dir/values-fr/values-fr.xml:273:49: Failed to flatten XML for resource 'no_fine_location_permissions' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:32:2: string/no_fine_location_permissions does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:141:2: Failed to flatten XML for resource 'no_imagery_available_for_area' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:141:2: string/no_imagery_available_for_area does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:92:2: Failed to flatten XML for resource 'no_surveys_available' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:92:2: string/no_surveys_available does not contain a valid string resource.
/home/runner/.gradle/caches/transforms-4/ebdaba96fc7f4b79a8c59e9a04d73490/transformed/jetified-ui-release/res/values-fr/values-fr.xml:10:4: Failed to flatten XML for resource 'no_tasks_error' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/.gradle/caches/transforms-4/ebdaba96fc7f4b79a8c59e9a04d73490/transformed/jetified-ui-release/res/values-fr/values-fr.xml:10:4: string/no_tasks_error does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:122:2: Failed to flatten XML for resource 'offline_area_list_item_icon' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:122:2: string/offline_area_list_item_icon does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:56:2: Failed to flatten XML for resource 'offline_area_selector_prompt' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:56:2: string/offline_area_selector_prompt does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:53:2: Failed to flatten XML for resource 'offline_area_viewer_remove_button' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:53:2: string/offline_area_viewer_remove_button does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:95:2: Failed to flatten XML for resource 'offline_icon_description' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:95:2: string/offline_icon_description does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:100:2: Failed to flatten XML for resource 'offline_map_imagery_download_progress_dialog_message' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:100:2: string/offline_map_imagery_download_progress_dialog_message does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/build/intermediates/incremental/localDebug/mergeLocalDebugResources/merged.dir/values-fr/values-fr.xml:303:57: Failed to flatten XML for resource 'offline_map_imagery_pref_description' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:43:2: string/offline_map_imagery_pref_description does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:116:2: Failed to flatten XML for resource 'read_only_data_collection_hint' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:116:2: string/read_only_data_collection_hint does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:177:2: Failed to flatten XML for resource 'remove_offline_access' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:177:2: string/remove_offline_access does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:25:2: Failed to flatten XML for resource 'report_summary' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:25:2: string/report_summary does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:[109](https://github.com/google/ground-android/actions/runs/11145054266/job/30973732464?pr=2770#step:5:110):2: Failed to flatten XML for resource 'selected_offline_area_size' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:109:2: string/selected_offline_area_size does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/build/intermediates/incremental/localDebug/mergeLocalDebugResources/merged.dir/values-fr/values-fr.xml:339:42: Failed to flatten XML for resource 'signup_request_access' with error: Attempting to flatten xml with unfinished spans.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:83:2: string/signup_request_access does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:[114](https://github.com/google/ground-android/actions/runs/11145054266/job/30973732464?pr=2770#step:5:115):2: Failed to flatten XML for resource 'survey_sync_hint' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:114:2: string/survey_sync_hint does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:80:2: Failed to flatten XML for resource 'switch_survey' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:80:2: string/switch_survey does not contain a valid string resource.
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:76:2: Failed to flatten XML for resource 'terms_of_service' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/ground-android/ground-android/ground/src/main/res/values-fr/strings.xml:76:2: string/terms_of_service does not contain a valid string resource.
/home/runner/.gradle/caches/transforms-4/9ec6c9f82180e127b3837635f05faa73/transformed/jetified-foundation-release/res/values-fr/values-fr.xml:2:4: Failed to flatten XML for resource 'time' with error: Invalid unicode escape sequence in string
"{str}"
```

**Comment by gino-m** [comment]
@jo-spek I fixed one issue - apparently `'` needs to be escaped with `\`. There are several other issues identified by Android Studio, namely missing translations, and some translations which actually aren't used. Did you translate these from `pt`? The `en` strings.xml has the complete list of strings needed.

The best way to resolve all of these issues is to open the project in Android Studio. There you'll see all off the potential issues highlighted inline, e.g.:

image

**Comment by jo-spek** [comment]
Oh, yes. Quite understandable that ' would cause problems. But the French diacritics are not a problem then? I'll go over it.

**Comment by shobhitagarwal1612** [comment]
You can also try adding changes in https://github.com/google/ground-android/pull/2771 to your branch.

**Comment by gino-m** [comment]
> Oh, yes. Quite understandable that ' would cause problems. But the French diacritics are not a problem then? I'll go over it.

I don't think the diacritics are a problem; I checked and they seem to be correctly encoded in UTF-8.

**Comment by gino-m** [comment]
@shobhitagarwal1612 added these in #2771 so we can close this. @kenstershiro please cmiiw.

**Comment by gino-m** [comment]
> Hey @gino-m , @shobhitagarwal1612 , to help me understand better, #2771 seems to have a commit on the french-translations branch, do we need an extra step to push these changes to master? And does 2771 include all the translations from Jonah above?

It looks like the French translations are already submitted. They should be appearing on new versions of the app on devices with French set as the system language.

**Comment by shobhitagarwal1612** [comment]
@gino-m French translations haven't been submitted yet. Should I revive #2771 again?

**Comment by gino-m** [comment]
> @gino-m French translations haven't been submitted yet. Should I revive #2771 again or the changes can be copied to this branch instead?

Reviving either is fine, provided @jo-spek 's commit history is preserved. Thanks @shobhitagarwal1612 !

**Comment by shobhitagarwal1612** [comment]
@gino-m Merged changes from #2771 to this branch. Please squash and merge to attribute the commit to @jo-spek.  PTAL?

**Pull request merged**
