### PR TITLE
Convert Submission classes to Kotlin

### PR DESCRIPTION
**Pull request by JSunde**

### CODE REVIEW

**Comment by JSunde** [comment]
PTAL @scolsen @gino-m

**Comment by JSunde** [comment]
It looks like there's a test that's failing because the toString of the TextResponse changed from "updated response" to "TextResponse(text=updated response)"

Is it important that we preserve the Response toString methods? Or is the new Data Class default implementation sufficient? (In which case I would just update the test)

**Review by gino-m — APPROVED** [review]
LGTM! 🐰

**Comment by gino-m** [comment]
> It looks like there's a test that's failing because the toString of the TextResponse changed from "updated response" to "TextResponse(text=updated response)"
> 
> Is it important that we preserve the Response toString methods? Or is the new Data Class default implementation sufficient? (In which case I would just update the test)

We chatted, ok to get rid of the custom `toString`!

**Pull request merged**
