### PR TITLE
[Polygon Drawing] Fixed styling issue for polygon  info dialog.

### PR DESCRIPTION
**Pull request by HemanParbhakar**
Contributes to #358 

This PR fixes styling issue of Polygon Dialog fragment UI Design as per the Figma.

@gino-m @atalekar  PTAL?

### CODE REVIEW

**Comment by HemanParbhakar** [comment]
gcbrun/

**Review by gino-m — CHANGES_REQUESTED** [review]
Please add screenshot to PR description, thanks!

**Comment by HemanParbhakar** [comment]
Screenshot_20210902_213130

**Pull request merged**
