### PR TITLE
hint text on offline map imagery list

### LINKED ISSUE #2118: Inconsistent hint text on offline map imagery list
When no imagery downloaded, text says to tap "Select and download", but the fab label is "Select area".

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2118 

@gino-m  PTAL?

### CODE REVIEW

**Comment by anandwana001** [comment]
@gino-m As per the Screenshot shown in Issue, we need the graphics to show above the text.

**Comment by shobhitagarwal1612** [comment]
Can you also add the image as per the mocks given in the bug?

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]
Left a comment

**Comment by anandwana001** [comment]
> Can you also add the image as per the mocks given in the bug?

Yes, in the above comment, I am asking to team to provide the graphics, do you know where I can get it?

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
