### PR TITLE
Show features on other map views

### LINKED ISSUE #1921: Show LOIs on map in other map views
- [x] Offline base map selector
- [x] Geospatial data collection tasks (suggest LOI and normal point/polygon data collection)

This is needed to help the data collector orient themselves wrt other LOIs.

### PR DESCRIPTION
**Pull request by JSunde**
Fixes #1921 1921

### CODE REVIEW

**Comment by JSunde** [comment]
@gino-m PTAL

**Review by gino-m — APPROVED** [review]
LGTM. Looks like there are some checks failing.

**Comment by JSunde** [comment]
Huh... I'm not sure I understand why it's failing. It's saying that it can't resolve lifecycleScope in DropAPinMapFragment, but that isn't something that I added 🤔

**Comment by JSunde** [comment]
Do you have any ideas @gino-m?

**Comment by gino-m** [comment]
> Do you have any ideas @gino-m?

Do tests pass when run locally?

**Comment by gino-m** [comment]
@JSunde `lifecycleScope` and `collect` are extension functions which need to be import; it looks like imports may have gotten deleted by the merge.

**Review by gino-m — APPROVED** [review]

**Pull request merged**
