### PR TITLE
Run unit tests and code quality checks in parallel

### LINKED ISSUE #1785: [Code health] Speed up GCB runs
Currently we run `checkCode` and `unitTests` in sequential order. These can be run in parallel to speed up the overall run by approx 2.5 mins

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1785

@... PTAL?

### CODE REVIEW

**Review by gino-m — APPROVED** [review]
Thanks!

**Comment by gino-m** [comment]
Failing with:

```
Gradle could not start your build.
> Cannot create service of type BuildSessionActionExecutor using method LauncherServices$ToolingBuildSessionScopeServices.createActionExecutor() as there is a problem with parameter #21 of type FileSystemWatchingInformation.
   > Cannot create service of type BuildLifecycleAwareVirtualFileSystem using method VirtualFileSystemServices$GradleUserHomeServices.createVirtualFileSystem() as there is a problem with parameter #7 of type GlobalCacheLocations.
      > Cannot create service of type GlobalCacheLocations using method GradleUserHomeScopeServices.createGlobalCacheLocations() as there is a problem with parameter #1 of type List<GlobalCache>.
         > Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
            > Timeout waiting to lock journal cache (/workspace/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
              Owner PID: 44
              Our PID: 44
              Owner Operation: 
              Our operation: 
              Lock file: /workspace/.gradle/caches/journal-1/journal-1.lock
```

Is this concurrency related? /gcbrun again in case it was a flake.

**Comment by shobhitagarwal1612** [comment]
Closing it for now

**Pull request closed without merging**
