### PR TITLE
[Nav drawer] Display selected survey details

### PR DESCRIPTION
**Pull request by gino-m**
Towards #2136

Include commits from #2371. Unfortunately I didn't have permission to push to that fork.

Screenshot_20240316_104251

@sufyanAbbasi @scolsen PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
@shobhitagarwal1612 Any idea what's going on with the tests? I see failures like:

```
Invalid ID 0x00000000.

Error performing 'single click' on view 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Offline map imagery"'.
androidx.test.espresso.PerformException: Error performing 'single click' on view 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Offline map imagery"'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
	at androidx.test.espresso.base.PerformExceptionHandler.handleSafely(PerformExceptionHandler.java:8)
	at androidx.test.espresso.base.PerformExceptionHandler.handleSafely(PerformExceptionHandler.java:9)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
	at com.google.android.ground.ui.home.NavigationDrawerItemClickTest$clickDrawerMenuItem$1$1.invoke(HomeScreenFragmentTest.kt:167)
	at com.google.android.ground.ui.home.NavigationDrawerItemClickTest$clickDrawerMenuItem$1$1.invoke(HomeScreenFragmentTest.kt:166)
	at com.google.android.ground.NavigationTestHelperKt$testNavigate$2.invokeSuspend(NavigationTestHelper.kt:72)
	at com.google.android.ground.NavigationTestHelperKt$testNavigate$2.invoke(NavigationTestHelper.kt)
	at com.google.android.ground.NavigationTestHelperKt$testNavigate$2.invoke(NavigationTestHelper.kt)
	at kotlinx.coroutines.flow.SubscribedFlowCollector.onSubscription(Share.kt:419)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:372)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
	at kotlinx.coroutines.flow.ReadonlySharedFlow.collect(Share.kt)
	at kotlinx.coroutines.flow.SubscribedSharedFlow.collect(Share.kt:409)
	at app.cash.turbine.FlowKt$collectIntoChannel$job$1.invokeSuspend(flow.kt:131)
	at app.cash.turbine.FlowKt$collectIntoChannel$job$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$collectIntoChannel$job$1.invoke(flow.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at app.cash.turbine.FlowKt.collectIntoChannel(flow.kt:129)
	at app.cash.turbine.FlowKt$collectTurbineIn$job$1.invokeSuspend(flow.kt:121)
	at app.cash.turbine.FlowKt$collectTurbineIn$job$1.invoke(flow.kt)
	at app.cash.turbine.FlowKt$collectTurbineIn$job$1.invoke(flow.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at app.cash.turbine.FlowKt.collectTurbineIn-5_5nbZA(flow.kt:120)
	at app.cash.turbine.FlowKt.access$collectTurbineIn-5_5nbZA(flow.kt:1)
	at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:55)
	at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
	at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at app.cash.turbine.FlowKt.test-C2H2yOE(flow.kt:54)
	at app.cash.turbine.FlowKt.test-C2H2yOE$default(flow.kt:49)
	at com.google.android.ground.NavigationTestHelperKt.testNavigate(NavigationTestHelper.kt:75)
	at com.google.android.ground.NavigationTestHelperKt.testNavigateTo(NavigationTestHelper.kt:54)
	at com.google.android.ground.NavigationTestHelperKt.testNavigateTo(NavigationTestHelper.kt:42)
	at com.google.android.ground.NavigationTestHelperKt.testMaybeNavigateTo(NavigationTestHelper.kt:103)
	at com.google.android.ground.ui.home.NavigationDrawerItemClickTest$clickDrawerMenuItem$1.invokeSuspend(HomeScreenFragmentTest.kt:166)
	at com.google.android.ground.ui.home.NavigationDrawerItemClickTest$clickDrawerMenuItem$1.invoke(HomeScreenFragmentTest.kt)
	at com.google.android.ground.ui.home.NavigationDrawerItemClickTest$clickDrawerMenuItem$1.invoke(HomeScreenFragmentTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:314)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:28)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:103)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:320)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:13)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:308)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:166)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:158)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
	at com.google.android.ground.BaseHiltTest.runWithTestDispatcher(BaseHiltTest.kt:50)
	at com.google.android.ground.ui.home.NavigationDrawerItemClickTest.clickDrawerMenuItem(HomeScreenFragmentTest.kt:159)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Unknown Source)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluateSafely(JUnitSessionStore.java:55)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:43)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:108)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:588)
	at app//org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at app//org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base@17.0.7/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base@17.0.7/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)
Target view: "AppCompatCheckedTextView{id=2131296450, res-name=design_menu_item_text, visibility=VISIBLE, width=200, height=41, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.LinearLayoutCompat$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=28.0, y=4.0, text=Offline map imagery, input-type=0, ime-target=false, has-links=false, is-checked=false}"
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:20)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:7)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:938)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:99)
	at android.os.Handler.dispatchMessage(Handler.java)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.doRun(ShadowPausedLooper.java:573)
	at org.robolectric.shadows.ShadowPausedLooper$ControlRunnable.run(ShadowPausedLooper.java:536)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:629)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:1)
	... 92 more
```

**Comment by shobhitagarwal1612** [comment]
I'm surprised to see `Sync status` test case isn't failing. Could it be a flake?

**Comment by gino-m** [comment]
> I'm surprised to see `Sync status` test case isn't failing. Could it be a flake?

Nope, it's reliably reproducible locally. I'm equally perplexed.

**Comment by shobhitagarwal1612** [comment]
Let's ignore the test class for now and proceed

**Comment by gino-m** [comment]
> Let's ignore the test class for now and proceed

Will do. Filed #2385 to track adding these tests back.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by scolsen** [comment]
awesome, thanks for picking this up @gino-m!

**Pull request merged**
