### PR TITLE
Added unit test for MutationDetail

### LINKED ISSUE #2567: [Code health] Add Unit Test for MutationDetail
Add Unit Test for MutationDetail

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2567 

@sufyanAbbasi  PTAL?

Screenshot 2024-07-23 at 1 17 40 PM

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Why do we need test coverage for a data class?

**Comment by anandwana001** [comment]
> Why do we need test coverage for a data class?

Yes, writing a separate test file might not require or can be covered with another dependent file, but
1. This file is mentioned in my task list as it's a 0% code coverage
2. IMO, writing test cases might look extra but it's good to have as we can say we have both dependent and independent test cases written which is helping us to achieve 100% code coverage 

WDYT?

**Comment by shobhitagarwal1612** [comment]
Adding coverage via this way doesn't achieve anything. I'd recommend not adding it. Instead, we should see which code flow should have covered these files and add tests for that. 

For e.g. MutationDetail object is created when displaying the SyncStatusFragment. So, adding unit tests for this fragment should automatically cover these files as well.

**Comment by anandwana001** [comment]
Got it, let me close this pr and we will cover it with the `SyncStatusFragment `. Thanks

**Pull request closed without merging**
