### PR TITLE
Add "Previous" button to data collection tasks

### LINKED ISSUE #1981: "Previous" button not shown on data collection tasks
See mocks for details

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1981

[previous_button.webm](https://github.com/google/ground-android/assets/8918023/b6b5412b-388a-43d6-a542-f5f378fac050)

@gino-m PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
> The build is failing due to
> 
> ```
>     android.view.InflateException
>         Caused by: android.view.InflateException
>             Caused by: java.lang.reflect.InvocationTargetException at SurveySelectorFragmentTest.kt:246
>                 Caused by: java.lang.OutOfMemoryError
> ```
> 
> @gino-m Any ideas if it could be related to any recent changes?

Trying this now, but it seems strange since `SurveySelectorFragmentTest` only has 238 lines.

**Review by gino-m — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
I think the issue is that GCB uses `N1_HIGHCPU_8` machine which has max 8 GB of ram.

**Comment by gino-m** [comment]
> I think the issue is that GCB uses `N1_HIGHCPU_8` machine which has max 7.2 GB of ram.
> 
> https://cloud.google.com/compute/docs/general-purpose-machines#n1_machine_types

Do these tests complete when run locally? Is it normal for Robolectric tests to require so much RAM, or could something else be going on here?

**Comment by shobhitagarwal1612** [comment]
The tests pass in the local environment only after increasing the memory limits. It seems unusual for unit tests to consume so much memory. I do remember seeing a bunch of warnings related to memory leakage when running the tests at HEAD as well.

**Comment by shobhitagarwal1612** [comment]
The issue is happening even if I remove the newly added unit tests and only keep the "previous" button related changes. So, there is no way to check-in the changes without breaking the build. I'll try understanding how to resolve the memory leakage issue which is causing the heap size to grow so big.

**Comment by gino-m** [comment]
> The issue is happening even if I remove the newly added unit tests and only keep the "previous" button related changes. So, there is no way to check-in the changes without breaking the build. I'll try understanding how to resolve the memory leakage issue which is causing the heap size to grow so big.

I see the same when running locally. The error only occurs when running multiple tests, running testing in `SurveySelectorFragmentTest` pass. Also seeing this error in unrelated tests like `com.google.android.ground.ui.signin.SignInFragmentTest`.

**Comment by shobhitagarwal1612** [comment]
I was able to generate the hprof file containing the heap dump. Analyzing it now.

**Comment by shobhitagarwal1612** [comment]
I also found that gradle.properties options aren't applied to unit tests. So, slightly increasing the heap size for unit tests should fix the problem. Tried looking at heap but wasn't able to narrow down to a specific issue. In general, a major chuck of memory was taken by `shadowVMRuntime` which is used by robolectric.

**Pull request merged**
