### PR TITLE
UI bug fixes

### PR DESCRIPTION
**Pull request by rachaprince**
Fixes two small bugs discovered during manual testing:

- Centers the custom icon in the crosshairs when adding points
- Prevents an Array index out of bounds error when removing vertices 

image

### CODE REVIEW

**Review by gino-m — APPROVED** [review]

**Comment by gino-m** [comment]
@rachaprince Looks like checkStyle is failing. You can run gradle `checkCode` target directly in AS to run all checks locally:
image

**Comment by rachaprince** [comment]
Thanks !

**Review by gino-m — APPROVED** [review]

**Review by gino-m — APPROVED** [review]

**Pull request merged**
