### PR TITLE
Refactor activate / sync survey process into use cases

### PR DESCRIPTION
**Pull request by gino-m**
Towards #1429. 

@shobhitagarwal1612 PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
?G

**Comment by gino-m** [comment]
@shobhitagarwal1612 RFAL! Thank you!

**Comment by shobhitagarwal1612** [comment]
License format seems to be incorrect for the added files. It doesn't expect `(c)`

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
