### PR TITLE
Remove Optional from response error state

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Towards #679

@gino-m  PTAL?

### CODE REVIEW

**Review by gino-m — APPROVED** [review]
This is cleaner, thanks!

**Review by gino-m — DISMISSED** [review]
This is cleaner, thank you!

**Comment by gino-m** [comment]
GCB is failing with:
```
Already have image (with digest): gcr.io/ground-android-gcb/android:28
ERROR: (gcloud.beta.firebase.test.android.run) argument --results-dir: expected one argument
Usage: gcloud beta firebase test android run [ARGSPEC] [optional flags]
  optional flags may be  --additional-apks | --app | --app-package | --async |
                         --auto-google-login | --client-details | --device |
                         --device-ids | --directories-to-pull |
                         --environment-variables | --filter |
                         --grant-permissions | --help | --limit | --locales |
                         --network-profile | --num-flaky-test-attempts |
                         --num-uniform-shards | --obb-files | --orientations |
                         --os-version-ids | --other-files | --page-size |
                         --performance-metrics | --record-video |
                         --results-bucket | --results-dir |
                         --results-history-name | --robo-directives |
                         --robo-script | --scenario-labels |
                         --scenario-numbers | --sort-by | --test |
                         --test-package | --test-runner-class | --test-targets |
                         --test-targets-for-shard | --timeout | --type |
                         --use-orchestrator

For detailed information on this command and its flags, run:
  gcloud beta firebase test android run --help
bash: line 7: --timeout: command not found
```

Any ideas?

**Comment by shobhitagarwal1612** [comment]
Strange! Let me try force-pushing to re-trigger the build.

**Comment by shobhitagarwal1612** [comment]
I've no idea why this is failing but the rest of them are working just fine

**Comment by gino-m** [comment]
> I've no idea why this is failing but the rest of them are working just fine

I think you need to quote values in the build script, specifically:

https://github.com/google/ground-android/blob/69984cd35e0c8d27795b17960bd5247261bd207e/cloudbuild.yaml#L131

This is likely failing because this PR's branch name contains a special char (`#`).

**Comment by shobhitagarwal1612** [comment]
Thanks Gino! PTAL again

**Review by gino-m — APPROVED** [review]
Ok to slip this commit into this PR - would you be able to quote the remaining args in a separate PR?

**Pull request merged**
