### PR TITLE
[WIP] Merge two instances of HiltTestActivity into one

### LINKED ISSUE #1334: [Code health] Merge the two HiltTestActivity classes

### PR DESCRIPTION
**Pull request by nikhil6624**
Have refactored the code by performing a safe delete of HiltTestActivity class which was lying redundantly(used by no other classes) in "staging" folder.

Fixes #1334

### CODE REVIEW

**Comment by nikhil6624** [comment]
@shobhitagarwal1612 , could you please look into this pull request?

**Comment by nikhil6624** [comment]
Hi @shobhitagarwal1612 , I have now fixed the failing Unit tests by adding the appropriate import statement in the UT class. Could you please review it now?

**Comment by shobhitagarwal1612** [comment]
It is still failing 

```

Step #5 - "Run unit tests": > Task :ground:compileStagingUnitTestKotlin FAILED
Step #5 - "Run unit tests": e: /workspace/ground/src/test/java/com/google/android/ground/HiltExt.kt: (26, 34): Unresolved reference: HiltTestActivity
Step #5 - "Run unit tests": e: /workspace/ground/src/test/java/com/google/android/ground/HiltExt.kt: (39, 21): Unresolved reference: HiltTestActivity
Step #5 - "Run unit tests": e: /workspace/ground/src/test/java/com/google/android/ground/HiltExt.kt: (42, 68): Unresolved reference: HiltTestActivity
Step #5 - "Run unit tests": e: /workspace/ground/src/test/java/com/google/android/ground/HiltExt.kt: (49, 27): None of the following functions can be called with the arguments supplied: 
Step #5 - "Run unit tests": public open fun <A : Activity!> launch(startActivityIntent: Intent!): ActivityScenario<TypeVariable(A)!>! defined in androidx.test.core.app.ActivityScenario
Step #5 - "Run unit tests": public open fun <A : Activity!> launch(activityClass: Class<TypeVariable(A)!>!): ActivityScenario<TypeVariable(A)!>! defined in androidx.test.core.app.ActivityScenario
Step #5 - "Run unit tests": e: /workspace/ground/src/test/java/com/google/android/ground/HiltExt.kt: (49, 34): Unresolved reference: HiltTestActivity
Step #5 - "Run unit tests": e: /workspace/ground/src/test/java/com/google/android/ground/HiltExt.kt: (49, 86): Cannot infer a type for this parameter. Please specify it explicitly.
S
```

**Comment by shobhitagarwal1612** [comment]
Please verify locally by running `./gradlew testStagingUnitTest`

**Comment by gino-m** [comment]
Hi @nikhil6624, thanks for the PR! Are you still working on this?

**Comment by nikhil6624** [comment]
Hi @gino-m , I have tried doing the best possible thing I could do and have pushed my relevant changes to this PR. It's a redundant file. It would be good to make a safe delete as I have done in my PR.

**Comment by gino-m** [comment]
> 

As mentioned by @shobhitagarwal1612, the file you deleted is presently required by the `staging` build; the version in `debug` is not accessible from `staging`. The task here is to also move the `debug` version to `sharedTest` to see if it's accessible to both builds. Please let us know if you have any questions, happy to clarify!

**Comment by gino-m** [comment]
Closing the PR as inactive for now. @nikhil6624 please feel free to submit the requested changes in a new PR if you would like to come back to it. Thanks!

**Pull request closed without merging**
