### PR TITLE
Basemap Viewer Fixes

### LINKED ISSUE #610: [Offline Base Map Details] Disable interactions with thumbnail map
Shouldn't be draggable/clickable

### PR DESCRIPTION
**Pull request by scolsen**
Addresses outstanding bugs and UI tweaks related to the Offline Basemap Viewer UI.

Fixes #610

### CODE REVIEW

**Comment by gino-m** [comment]
@scolsen Gentle ping!

**Comment by scolsen** [comment]
Fixes #611, #612

**Comment by scolsen** [comment]
Fixes #613 

Screen Shot 2020-12-08 at 9 45 18 AM

**Review by gino-m — APPROVED** [review]
Nicely done! 👏 🎉

**Pull request merged**
