### PR TITLE
Update launcher icon

### PR DESCRIPTION
**Pull request by gino-m**
Adds missing white stroke. @vittorino PTAL?

Before:
image

After:
image

Image source:
ground-logo

### CODE REVIEW

**Review by vittorino — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
The GCB runs have been flaky since past few days. Retrying the task usually helps.

**Comment by shobhitagarwal1612** [comment]
Can you please try running the `checkCode` command locally and resolve any findings? I'll look into why the CI is failing so frequently.

**Comment by gino-m** [comment]
> Can you please try running the `checkCode` command locally and resolve any findings? Then we can unblock this PR and merge it as is.
> 
> I'll look into why the CI is failing so frequently.

It seems there was an unused resource added by the Android Studio launcher icon import tool (?). Removing it lint check pass locally. Trying again w/CI.

/gcbrun

**Pull request merged**
