### PR TITLE
Rename Feature -> LocationOfInterest

### PR DESCRIPTION
**Pull request by scolsen**
Renames all instances of Feature to LocationOfInterest *except* for classes in `persistence/remote/` (model classes in these packages are renamed, however, to ensure the code builds).

Also renames `PointFeature` to `PointOfInterest` and `PolygonFeature` to `PolgyonOfInterest`.

Contributes to #1114

### CODE REVIEW

**Comment by gino-m** [comment]
Cool, thanks! How does spelling out LOI feel so far? Acceptable or burdensome?

> Also renames PointFeature to PointOfInterest and PolygonFeature to PolgyonOfInterest.

Going forward I don't think we'll need separate classes for different typing of LOIs; they'll just have Geometry which will contain that complexity. We'll still have to model MultiPolygon, Point, etc. but I believe we already have those modeled elsewhere. No changed needed in this PR, just wanted it to be on everyone's radar.

**Comment by scolsen** [comment]
oops, not sure why there's a bunch of errorprone errors for generated code

**Comment by shobhitagarwal1612** [comment]
gentle ping!

**Review by shobhitagarwal1612 — APPROVED** [review]
Thanks!

**Pull request merged**
