### PR TITLE
Create shared layout for basemap + ui controls

### LINKED ISSUE #1365: [GPS Data Collect] Create shared layout classes for basemap + ui controls
Context: https://github.com/google/ground-android/pull/1362

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1365

Basic prototype: https://github.com/google/ground-android/pull/1362

This PR aims at creating shared layouts for setting up basemap along with user interaction functionality. These shared classes would be used by MapContainerFragment and upcoming Data Collection fragments.

This includes:

1. Create a basemap_layout with map frame, gps lock button and map type button
2. Refactor home layout and map container layout

Verified by installing the app locally and interacting with the map.

@gino-m PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
@shobhitagarwal1612 Thanks for the PR! A few initial thoughts for discussion:

* Since we're using fused location and not just GPS, please `s/Capture GPS/Capture location/g`.
* We haven't nailed down the UX for capture location yet, but as a starting point we can assume it will be identify to "Drop a pin", with the exception that a) the map cannot be panned or zoomed, and b) location lock is on and cannot be turned off.

Let's discuss in more detail offline.

**Comment by shobhitagarwal1612** [comment]
Sure. Thanks for taking a look!

**Comment by shobhitagarwal1612** [comment]
@gino-m I've rebased this PR. This is ready for a review

**Review by gino-m — APPROVED** [review]
LGTM! Please just remove "GPS Data Collect" from the PR title before merging.

**Pull request merged**
