### PR TITLE
Update to gradle 7.0.3

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Updates gradle to 7.0.3

* Improves code coverage stats by excluding remaining auto-generated classes
* Removes unused `powermock` library
* Updates dependent navigation and hilt libraries

@gino-m  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
I'll try splitting it into multiple PRs. The dependent changes could be checked-in separately.

**Comment by gino-m** [comment]
> I'll try splitting it into multiple PRs. The dependent changes could be checked-in separately.

@shobhitagarwal1612  How far did we get on this? Should we close this PR for now?

**Comment by shobhitagarwal1612** [comment]
Sorry, I forgot about this. Will definitely take up next.

**Review by gino-m — DISMISSED** [review]
🚀

**Comment by shobhitagarwal1612** [comment]
@gino-m Can I get a re-stamp? Linter was failing.

**Comment by shobhitagarwal1612** [comment]
Codecov seems to be broken as well. Marking this back to draft.

**Review by gino-m — APPROVED** [review]

**Pull request merged**
