### PR TITLE
Initial pass at switching to use new theme colors

### PR DESCRIPTION
**Pull request by JSunde**

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Are there any major changes in the UI?

**Comment by JSunde** [comment]
image
image
image
image

**Comment by shobhitagarwal1612** [comment]
I believe there used to be a light green background behind the action buttons.

**Comment by shobhitagarwal1612** [comment]
Can you please check the latest figma mocks?

**Comment by JSunde** [comment]
> I believe there used to be a light green background behind the action buttons.

Which action buttons are you referring to?

**Comment by JSunde** [comment]
> > I believe there used to be a light green background behind the action buttons.
> 
> Which action buttons are you referring to?

I think that the changes I've made so far have been swapping colors for other colors that are very close, so I think if there's an issue with a component being the wrong color we should maybe follow up on that separately so I think I'll go ahead with this CL as is.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
