### PR TITLE
Remove unused LocationOfInterestDataTypeSelectorDialogFragment

### LINKED ISSUE #1665: Cleanup LocationOfInterestDataTypeSelectorDialogFragment and it's tests
LocationOfInterestDataTypeSelectorDialogFragment is no longer used and should be cleaned up.

### PR DESCRIPTION
**Pull request by devedroy**
## fixes #1665 
Done Cleanup of LocationOfInterestDataTypeSelectorDialogFragment and it's tests

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
> /gcbrun

This command currently works only if added by a repository collaborator. We can think about adding support for it in the future. In meantime, please run the gradle tasks locally to ensure there are no failures before raising a CL

**Review by JSunde — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
@devedroy Can you please resolve the conflicts?

**Comment by devedroy** [comment]
Please check out, I have pushed the changes.
Thankyou.

**Comment by devedroy** [comment]
Seems like the merge added the strings again, let me recheck and push.
Sorry for the inconvenience.

**Pull request merged**
