### PR TITLE
[Photo] Add label to photo type fields

### LINKED ISSUE #684: [Add/edit observation] Field labels not showing for photo fields
@shobhitagarwal1612 Could you confirm that the labels show about photo fields? I inferred they might not from screenshots in your recent PR. Thanks!

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #684

Adds label and background to photo fields to make it consistent with other input types.

@gino-m  PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
Thanks @shobhitagarwal1612 for adding the field labels! What does it look like after a photo is added?

@coreyleamon Could you PTAL and advise on UX?

**Comment by shobhitagarwal1612** [comment]
Also removed the material card.

Screenshot:

**Comment by coreyleamon** [comment]
I would actually recommend a different treatment for images, rather than loading an image inside a text input. We'll also need to consider if an image has representation in the observation summary screen. I can mock something up in the next couple days.

**Comment by gino-m** [comment]
> I would actually recommend a different treatment for images, rather than loading an image inside a text input. We'll also need to consider if an image has representation in the observation summary screen. I can mock something up in the next couple days.

@coreyleamon, that would be super helpful! I've create #738 to track and to unblock the incremental improvements made here. Thanks for taking a look!

**Comment by gino-m** [comment]
@coreyleamon Gentle ping in case you're able to comment on this. If you can't no worries at all, just let me know and I'll look for precedent in similar Android Material apps!

**Comment by gino-m** [comment]
Shobhit isn't currently available, so merging this PR for now. We can refine the UI details going forward. 

@coreyleamon Could you please create a feature request with mocks for the updated photo field treatment?

**Review by gino-m — APPROVED** [review]

**Pull request merged**
