### PR TITLE
Pull out the Data Collection Task header into subcomponent

### PR DESCRIPTION
**Pull request by JSunde**
Added a new subcomponent view for the Data Collection Task header so it can be reused between different task fragments

Towards #1146 

@shobhitagarwal1612 PTAL

### CODE REVIEW

**Comment by JSunde** [comment]
Let me know if you have any ideas why the tests are failing now. I ran the app on my device and it seems to be working properly so I don't know why I'm getting these errors:

```
is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
     Got: "MaterialTextView{id=2131230879, res-name=data_collection_question, visibility=VISIBLE, width=6, height=65, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@5a5f1e45, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=41.0, text=task 1, input-type=0, ime-target=false, has-links=false}"
```

**Comment by shobhitagarwal1612** [comment]
All of the view assertions are failing. I'll try to take a look at it today.

**Comment by scolsen** [comment]
@JSunde so, it's subtle, but a one-line change made it such that the view is not actually visible. Change the constraint on `data_collection_question` back to `app:layout_constraintTop_toBottomOf="@+id/data_collection_task_name" />`

**Comment by JSunde** [comment]
Thanks @scolsen! I took a closer look and I think there were actually a couple things wrong with the constraints there, I ended up constraining the top to the bottom of `data_collection_step_number` and the bottom to the bottom of the parent and now it seems to be passing the test and looks correct on my device.

**Review by scolsen — APPROVED** [review]

**Pull request merged**
