### PR TITLE
Load Suggest Loi Tasks and render cards for them

### PR DESCRIPTION
**Pull request by JSunde**
Towards #1637

### CODE REVIEW

**Comment by JSunde** [comment]
For some reason there don't seem to be any jobs loaded in the SuggestLoiJobs LiveData.

I already added a new "Suggest LOI" job to the survey with the suggestTaskType of "point", but there don't seem to be any jobs loaded with that suggestionTaskType.

@shobhitagarwal1612 @scolsen do either of you have any ideas? I'm guessing I maybe missed something in the creation of Job objects, but I'm not sure.

**Comment by shobhitagarwal1612** [comment]
Is the new object getting saved to local data store? LoiCards data is read from cached local storage and not directly from firebase.

**Comment by JSunde** [comment]
Are jobs not persisted to the local data store?

**Comment by shobhitagarwal1612** [comment]
The model is serialised and deserialized when storing locally. So, you might have missed adding new fields in the existing job model

**Comment by JSunde** [comment]
Do you have any idea  where that would be? I'm not as familiar with the local data store, and I thought I updated all of the places I needed to:
- JobConverter
- Job
- JobNestedObject

**Comment by shobhitagarwal1612** [comment]
That would be JobEntity class

**Comment by JSunde** [comment]
Ah okay, thanks! It looks like I was missing the suggestLoiTaskType in the JobEntity and some logic in ConvertExt.

It looks like when the app first loads up the Suggest LOI job is present, but then it is missing on subsequent loads, any ideas what I might be missing now?

**Comment by shobhitagarwal1612** [comment]
> It looks like when the app first loads up the Suggest LOI job is present, but then it is missing on subsequent loads, any ideas what I might be missing now?

I'll take a look at the code. My first guess would be to look at the filtering logic and ensure we are not implicitly removing the suggest LOIs.

**Comment by shobhitagarwal1612** [comment]
Is this PR ready for a review?

**Pull request merged**
