### PR TITLE
Add tests for FeatureDataTypeSelectorFragment

### PR DESCRIPTION
**Pull request by JSunde**
@shobhitagarwal1612 PTAL

### CODE REVIEW

**Review by shobhitagarwal1612 — DISMISSED** [review]

**Comment by JSunde** [comment]
Huh, do you think that file was already covered by other tests @shobhitagarwal1612? I'm surprised that there was no impact on code coverage.

**Comment by shobhitagarwal1612** [comment]
Have you tried looking at the code coverage for that file locally? It should be somewhere under jacoco/ directory.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Review by shobhitagarwal1612 — APPROVED** [review]
Thanks!

**Review by gino-m — APPROVED** [review]
LGTM, thanks!

**Comment by JSunde** [comment]
Since the CodeCov report may be innaccurate because it wasn't calculating the coverage for @AndroidEntryPoints classes before, here are the before and after results for the mapcontainer directory.

Before:
image

After:
image

So the coverage was increased by 4% from 16% to 20%

**Pull request merged**
