### PR TITLE
[Bug] Open project selector dialog only once

### LINKED ISSUE #1084: [Project selector] Dialog opened multiple times on config change
1. Sign in
2. Accept ToS
3. When project dialog appears, rotate device
4. Rotate device again
5. Multiple dialogs appear, tapping an item closes top dialog revealing dialog underneath.

This could be causing exception found in Crashlytics:
```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: ProjectSelectorDialogFragment{b2d0f68} (72f78b3b-3565-409b-90a5-2e1a1bd4e222 tag=ProjectSelectorDialogFragment)
       at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:91)
       at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1713)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:415)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2404)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2162)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3030)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at com.google.android.gnd.AbstractActivity.onStart(AbstractActivity.java:73)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1521)
       at android.app.Activity.performStart(Activity.java:7838)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3399)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1084

Replaces manual dialog handling with navigation component.
https://medium.com/androiddevelopers/navigation-component-dialog-destinations-bfeb8b022759

This refactor is currently applied to `ProjectSelectorDialogFragment` and `FeatureSelectorFragment`. The remaining dialog fragments pass unserializable/unparcelable data or callback to the fragment. They would need a bigger refactor before the same solution can be applied to them.

Steps to verify:

1. Sign in
2. Accept ToS
3. When project dialog appears, rotate the device

@gino-m PTAL?

### CODE REVIEW

**Review by JSunde — CHANGES_REQUESTED** [review]
Would it be possible to add tests verifying that the FeatureSelectorFragment is launched from the HomeScreen?

**Comment by shobhitagarwal1612** [comment]
@JSunde Do we want to add tests for feature selector given that the flow is about to change?

**Comment by shobhitagarwal1612** [comment]
@JSunde Do we want to add tests for feature selector given that the flow is about to change?

**Comment by JSunde** [comment]
> @JSunde Do we want to add tests for feature selector given that the flow is about to change?

Synced offline and decided it wasn't worth the effort since we plan to remove the functionality for users to add features.

**Review by JSunde — APPROVED** [review]

**Pull request merged**
