### PR TITLE
[CI] Run instrumentation tests on GCB

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Run instrumented tests on firebase test lab

* Enabled "Cloud tools results" API. Needed for accessing results from developer tools.

* The live status of test execution is streamed to the linked firebase project:
Open firebase console > Select project > Test lab

* gcloud docker image
https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcloud

@gino-m  PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
LG so far! What else is left to do before we can review + merge?

**Comment by gino-m** [comment]
Please continue using the previous GCB project as discussed.

**Comment by shobhitagarwal1612** [comment]
The failing test is a fluke. Should I disable it for now?

**Comment by shobhitagarwal1612** [comment]
@gino-m @dturner @scolsen PTAL

**Comment by shobhitagarwal1612** [comment]
Improved overall execution time by 50% using parallel workflows

New workflow:
Screenshot 2020-11-24 at 3 49 19 PM

**Comment by dturner** [comment]
Amazing work as always @shobhitagarwal1612. 

The flaky behaviour you see might be caused by animations not being disabled on the target device. In theory it should be possible to disable animations with the following adb commands: 

```
adb shell settings put global window_animation_scale 0
adb shell settings put global transition_animation_scale 0
adb shell settings put global animator_duration_scale 0
```

Do you want to give that a try and see if it fixes the flaky test?

**Comment by shobhitagarwal1612** [comment]
@dturner I'm not sure how to pass adb commands to firebase testlab.
These are all the flags that can be configured
https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/android/run

**Comment by gino-m** [comment]
@shobhitagarwal1612 Very cool! 

Re flakiness due to animations, does this help at all?
https://medium.com/@balachandarkm/disable-animations-while-running-android-ui-tests-2d1748280156

**Comment by shobhitagarwal1612** [comment]
> Re flakiness due to animations, does this help at all?
https://medium.com/@balachandarkm/disable-animations-while-running-android-ui-tests-2d1748280156

No, it did not help. I've disabled it for now so that we can proceed with merging this PR. 
We will have to rely on manually running this test until we have a solution.

PTAL again

**Review by gino-m — APPROVED** [review]
Sorry for the delay, LGTM!

**Pull request merged**
