### PR TITLE
[Code health] Update to gradle plugin version 4.0

### PR DESCRIPTION
**Pull request by dturner**
Upgrade to gradle plugin to 4.0.0 and some other version bumps, notably:

- Remove `android.enableUnitTestBinaryResources=true`. [No longer needed since Android 3.3](http://robolectric.org/blog/2018/10/25/robolectric-4-0/).
- Remove `android.enableSeparateAnnotationProcessing=true`. [No longer supported in Gradle Plugin 4.0.0](https://developer.android.com/studio/releases/gradle-plugin) (see section titled "Separate annotation processing feature removed")
- Update com.google.android.gms:play-services-base:17.2.1 to 17.3.0
- Update gradle version to 6.5

Problem:

Spotbugs gives an error so is currently commented out. Need expert help from @gino-m :)

### CODE REVIEW

**Comment by dturner** [comment]
When I uncomment `apply from: '../config/spotbugs/spotbugs.gradle'` in `gnd/build.gradle` I get the following error: 

```
Warning:<i><b>project ':gnd': Unable to build Kotlin project configuration</b>
Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':gnd:spotbugs'.
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'SpotBugsTask'.
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.github.spotbugs.internal.SpotBugsReportsImpl.
Caused by: java.lang.NoSuchMethodError: org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V</i>```

**Comment by gino-m** [comment]
> When I uncomment `apply from: '../config/spotbugs/spotbugs.gradle'` in `gnd/build.gradle` I get the following error:
> 
> ```
> Warning:<i><b>project ':gnd': Unable to build Kotlin project configuration</b>
> Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':gnd:spotbugs'.
...
> ```

I see this as well, but it appears to be a warning and not an error. I can build successfully, but when trying to run I get:
```
Unable to find method 'org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by gino-m** [comment]
Updated: Lowered Gradle wrapper version to 6.1.1 recommended [here](https://developer.android.com/studio/releases/gradle-plugin) and got:

```
<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>/Users/gmiceli/Projects/gino-m/ground-android/gnd/build.gradle<ij_nav><i><b>project ':gnd': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':gnd:spotbugs'.<eol>Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'SpotBugsTask'.<eol>Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.github.spotbugs.internal.SpotBugsReportsImpl.<eol>Caused by: java.lang.NoSuchMethodError: org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V</i>
```

**Comment by gino-m** [comment]
Looking through the docs and various posts, it seems a lot has changed between spotbugs 1.x and 4.x  I'm having a hard time understanding the delta here; it would probably make sense to remove the spotbugs plugin altogether and adding back based on the latest docs. Unfortunately the docs for doing this in Android projects are still "TBD" in the README ([link](https://github.com/spotbugs/spotbugs-gradle-plugin#apply-to-android-project)). I wonder if we can figure this out based on the instructions for using w/Java? 

@shobhitagarwal1612 would you be able to take a peek?

**Comment by shobhitagarwal1612** [comment]
Sorry for mentioning this so late, but I already started looking into this bug a few weeks ago (updating spotbugs). I thought I mentioned this to @gino-m but forgot to open an issue.

@dturner I think it's fine to disable this plugin temporarily until it is resolved. We shouldn't halt updating gradle version because of this. You can just remove the `spotbugs` from the `checkCode` gradle task (in root level build.gradle) to stop running it automatically.

**Comment by dturner** [comment]
Many thanks for the comments and quick review. I've commented out spotbugs for the time being as per @shobhitagarwal1612 suggestion.

**Comment by dturner** [comment]
Looks like [this is the related spotbugs issue](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/105)

**Pull request merged**
