### PR TITLE
[Regression] Make MapProvider singleton

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
MapProvider is injected into both `FeatureRepositionView` and `MapContainerFragment`. Without a singleton, each would have a different copy of MapProvider.

@gino-m PTAL?

### CODE REVIEW

**Review by gino-m — COMMENTED** [review]
The provider actually contains a reference to a map inside `MapAdapter`. Do the offline areas area selector or thumbnail view need a new instance, or is ok for them to reuse the same one?

**Comment by shobhitagarwal1612** [comment]
I tested locally and the offline areas selected is working fine with the above changes.

**Review by gino-m — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
