### PR TITLE
Update todo-to-list github action to commit to PR instead of master branch

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Instead of merging the commit to master branch, it commits to the PR's source branch when the PR is approved.

@gino-m  PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
@shobhitagarwal1612 Should we move this to draft for now?

**Review by gino-m — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
@gino-m The workflow isn't able to find the email if the workflow is run after PR is approved automation.

**Comment by gino-m** [comment]
> @gino-m The workflow isn't able to find the email if the workflow is run after PR is approved automation.

Which email are you referring to?

**Comment by shobhitagarwal1612** [comment]
In order to bypass cla/google check, I added a step to get the email from `github.head_ref` and use that when committing the new changes from workflow. This works fine when the workflow is executed on commit push. When the workflow is triggered on PR approval, then the step to get email doesn't work.

**Comment by gino-m** [comment]
> In order to bypass cla/google check, I added a step to get the email from `github.head_ref` and use that when committing the new changes from workflow. This works fine when the workflow is executed on commit push. When the workflow is triggered on PR approval, then the step to get email doesn't work.

I see. Only maintainers can push to this repo, so perhaps allowing creation of TODOs on commit is acceptable?

**Comment by shobhitagarwal1612** [comment]
> I see. Only maintainers can push to this repo, so perhaps allowing creation of TODOs on commit is acceptable?

Agreed. If you also agree, I can update this PR to run the workflow on each commit push.

**Comment by gino-m** [comment]
> > I see. Only maintainers can push to this repo, so perhaps allowing creation of TODOs on commit is acceptable?
> 
> Agreed. If you also agree, I can update this PR to run the workflow on each commit push.

Sure, let's do it!

**Pull request merged**
