### PR TITLE
Rename Observation -> Submission

### PR DESCRIPTION
**Pull request by JSunde**
Addresses one of the planned renames from #1114

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
We should also update the db schema version in Config.

**Comment by JSunde** [comment]
> We should also update the db schema version in Config.

Is that as simple as bumping the DB_VERSION?

**Comment by shobhitagarwal1612** [comment]
> Is that as simple as bumping the DB_VERSION?

Yes lets increment that by +1. This would ensure that the existing apps auto-clear the db. Otherwise the app would fail to load.

**Review by shobhitagarwal1612 — APPROVED** [review]
LGTM

**Pull request merged**
