### PR TITLE
Convert Option to Kotlin

### PR DESCRIPTION
**Pull request by JSunde**

### CODE REVIEW

**Comment by JSunde** [comment]
@gino-m Any ideas why the @Serializable annotation doesn't seem to be working properly?

**Comment by JSunde** [comment]
> @gino-m Any ideas why the `@Serializable` annotation doesn't seem to be working properly?

Actually I think I was able to resolve this after following the setup instructions here: https://github.com/Kotlin/kotlinx.serialization#setup

**Comment by gino-m** [comment]
> @gino-m Any ideas why the `@Serializable` annotation doesn't seem to be working properly?

I was just looking into this, I see you found a fix!

**Review by gino-m — APPROVED** [review]
LGTM!

**Pull request merged**
