### PR TITLE
[UX] Fix navigation menu icon

### LINKED ISSUE #835: Navigation menu icon not visible on lighter backgrounds
**Describe the bug**
The hamburger menu/navigation icon is not visible on lighter backgrounds.

**Expected behavior**
Temporarily replace floating icon with dark icon within white circle, similar to other navigation elements on screen like base map layer and center GPS.

**Screenshots**
Screenshot_20210601-144541_Ground

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #835

| Before | After |
| :------------- | :----------: |
| image | image |

@gino-m  PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
Great idea! Checks seem to be failing, otherwise LGTM.

**Comment by shobhitagarwal1612** [comment]
I wish there were a way to auto-trigger code checks on `git push` ✨

**Comment by shobhitagarwal1612** [comment]
The gradle crashed while building the apk. Re-running the remote build.

**Comment by gino-m** [comment]
Failed again, trying one more time.

**Comment by shobhitagarwal1612** [comment]
PTAL

**Review by gino-m — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
