### PR TITLE
[Code health] Update dependencies

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Periodic updates.

@gino-m PTAL?

### CODE REVIEW

**Review by gino-m — APPROVED** [review]
LGTM! ⬆️  📅

**Comment by gino-m** [comment]
@shobhitagarwal1612 Any idea Gradle is crashing?

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by shobhitagarwal1612** [comment]
The gradle doesn't fail locally. Maybe a fluke?

**Comment by gino-m** [comment]
> The gradle doesn't fail locally. Maybe a fluke?

I manually reran the build and it failed again. Perhaps one of the upgrades is incompatible with GCB?

**Comment by shobhitagarwal1612** [comment]
Let's close this and do an incremental upgrade of dependencies.

**Pull request closed without merging**
