### PR TITLE
Added a unit test for UserRepository SignOut 

### LINKED ISSUE #2569: [Code health] Add User Repository SignOut Unit Test
Add User Repository SignOut Unit Test

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2569 

@sufyanAbbasi  PTAL?

### CODE REVIEW

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by sufyanAbbasi** [comment]
Seems to be a weird transient error, rerunning: 

/gcbrun

**Comment by anandwana001** [comment]
Checks are passing locally

**Comment by shobhitagarwal1612** [comment]
We can merge since they are passing locally.

**Pull request merged**
