### PR TITLE
Draft change getting Jetpack Compose working in Ground

### PR DESCRIPTION
**Pull request by JSunde**

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Thanks @JSunde! Can we keep this PR around until I get to integrating this with the task buttons?

**Comment by gino-m** [comment]
@JSunde Is this PR still valid? If not, can we close it for now?

**Comment by JSunde** [comment]
I think it's still valid, and might be useful as a reference if we decide we want to start using Jetpack Compose for any new UIs.

We can always re-open it if we close it, right? If so then I think we could close it and can dig it up for reference later.

**Comment by gino-m** [comment]
Sg, I'll close it for now. I've created a bug to tracked and linked to this PR so we can find it.

**Pull request closed without merging**
