### PR TITLE
Renamed SubmissionStore -> LocalSubmissionStore

### LINKED ISSUE #1590: Rename local store interfaces to include `Local` prefix
In `com.google.android.ground.persistence.local.stores`
* `MutationStore` -> `LocalMutationStore`
* `SubmissionStore` -> `LocalSubmissionStore`

### PR DESCRIPTION
**Pull request by devedroy**
Fixes #1590 

I tried renaming the Class and file names and the KFTMT throws the following error:

image

I have manually checked the file formats and it looks good to me.
Can you please have a look and guide me on what could be the possible issue?
Thankyou.

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Run `ktfmtFormat` locally to auto-format the files and then rerun `checkCode`

**Comment by shobhitagarwal1612** [comment]
Hey @devedroy! Any updates on this?

**Comment by devedroy** [comment]
Hello @shobhitagarwal1612 
I'm still facing the same issue!!

**Comment by shobhitagarwal1612** [comment]
Did you try running `ktfmtFormat` as mentioned in https://github.com/google/ground-android/pull/1670#issuecomment-1532494223?

**Comment by devedroy** [comment]
Yes, I did it and this is what the compiler has to say after that.
image

**Comment by shobhitagarwal1612** [comment]
Looks good! These are just warnings. You can push your latest changes and I can trigger the build after that.

**Comment by devedroy** [comment]
Done, I have pushed my latest change.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
