### PR TITLE
[Code health] Tweak license header check

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
It is annoying when Android Studio wraps the header's first line in xml when running `auto-format`.

`<?xml version="1.0" encoding="utf-8"?>`

Since it is optional and doesn't add much value to the code since Android Studio is smart enough to handle them anyways, I propose that we remove them.

So, this PR aims at reducing the developer's time wasted at reverting back the changes manually.
Also, enables the license header check for all xml files and not just under `layout` dir

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Another solution would be to introduce a blank space between the xml declaration tag and license.
@gino-m @scolsen Penny for a thought?

**Comment by shobhitagarwal1612** [comment]
Now with the updated checkstyle template, it will be notified with the checkCode task

**Comment by shobhitagarwal1612** [comment]
But we'll still need to remove it manually

**Comment by gino-m** [comment]
These headers seem to be recommended, and are used fairly consistently in the Android sources, for example:
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/res/res/layout/

It seems adding a blank line between the XML declaration and the comment stops to formatter from removing the newline.

**Comment by shobhitagarwal1612** [comment]
SGTM

**Pull request merged**
