### PR TITLE
Switch more colors to new theme

### PR DESCRIPTION
**Pull request by JSunde**

### CODE REVIEW

**Comment by JSunde** [comment]
image
image
image

**Comment by JSunde** [comment]
> From the above screenshot, it appears that background color is now light green. Is that correct?

Yes I believe that's correct, I'm using `md_theme_surface` from the new theme which is defined as F9FAF4 which is lightly tinted green.

**Comment by JSunde** [comment]
And colorSurface is generally used for the default background in Android apps.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
