### PR TITLE
[Code health] Rename classes to use correct names for various Firebase products

### PR DESCRIPTION
**Pull request by gino-m**
@scolsen PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
```
Step #9 - "Update build status": Execution failed for task ':workspace:ground:ktfmtCheckMain'.
Step #9 - "Update build status": > [ktfmt] Found 1 files that are not properly formatted:
Step #9 - "Update build status":   /workspace/ground/src/main/java/com/google/android/ground/persistence/remote/RemoteStorageModule.kt
```

**Review by scolsen — APPROVED** [review]

**Comment by gino-m** [comment]
> ```
> Step #9 - "Update build status": Execution failed for task ':workspace:ground:ktfmtCheckMain'.
> Step #9 - "Update build status": > [ktfmt] Found 1 files that are not properly formatted:
> Step #9 - "Update build status":   /workspace/ground/src/main/java/com/google/android/ground/persistence/remote/RemoteStorageModule.kt
> ```

@shobhitagarwal1612 Any idea where the offending formatting is? I don't see anything suspicious..

**Comment by shobhitagarwal1612** [comment]
We can just run ktfmtFormat and it will automatically format the code for us

**Comment by scolsen** [comment]
> > ```
> > Step #9 - "Update build status": Execution failed for task ':workspace:ground:ktfmtCheckMain'.
> > Step #9 - "Update build status": > [ktfmt] Found 1 files that are not properly formatted:
> > Step #9 - "Update build status":   /workspace/ground/src/main/java/com/google/android/ground/persistence/remote/RemoteStorageModule.kt
> > ```
> 
> @shobhitagarwal1612 Any idea where the offending formatting is? I don't see anything suspicious..

I think I've run into it not liking very subtle things like the line a `])` appears on.

**Comment by shobhitagarwal1612** [comment]
I ran the command locally. The import order is incorrect.

**Comment by gino-m** [comment]
> I ran the command locally. The import order is incorrect.

When I ran `gradle ktfmtFormat` there were no changes, now I see the import order being fixed; not sure what happened! Pushing the fixes.

**Pull request merged**
