### PR TITLE
Fix survey not visible even when ACLs are present

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Firebase uses "survey_organizer" whereas android app expects "survey-organizer". 

Verified by manually setting the ACL to "survey_organizer" in firebase and running the app locally.

@JSunde  PTAL?

### CODE REVIEW

**Comment by JSunde** [comment]
Hmm, I seem to remember Gino telling me to change them from "survey_organizer" and "data_collector" to "survey-organizer" and "data-collector". Let me see if I can find the context on that.

**Comment by JSunde** [comment]
Hmm, well unfortunately I didn't provide more context in the PR where I made that change... Let me see if I can find anything in chat.

**Comment by JSunde** [comment]
Here is the context from our chat:

```
it seems survey_organizer isn't recognized as a role
...
Are you ok with "survey-organizer" as role key?
If so I'll manually edit it in the db, but you'll need to update it in the Android app
same for "data-collector" (instead of data_collector)
...
Firebase's schema is JSON like so seems tk make more sense to use slug case
```

So I'm wondering if we need to update the roles in Firebase?

**Comment by shobhitagarwal1612** [comment]
Thanks for the context! Will update the db manually

**Pull request closed without merging**
