### PR TITLE
Display license and terms of service 

### LINKED ISSUE #2326: [Compliance] Display licenses and ToS in app
Potentially using https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #2326

* Adds 2 new entries in the app drawer: "About" and "Terms of service"
* Clicking on "About" opens a new screen with hyperlinks to apache license and other licenses
* Clicking on "Terms of service" opens the original terms of service screen with checkbox and accept button hidden

[license_tos.webm](https://github.com/google/ground-android/assets/8918023/bbfed8cf-c80f-491a-899d-7ac86474ef56)

@sufyanAbbasi @gino-m  PTAL?

### CODE REVIEW

**Comment by rawbzz** [comment]
wait are we not moving sign out to the profile icon? But yes, about and terms of service should be last on the list!

**Comment by shobhitagarwal1612** [comment]
"Sign out" will be moved in a separate PR.

**Comment by shobhitagarwal1612** [comment]
I'll move "settings" above "about"

**Review by gino-m — COMMENTED** [review]
@sufyanAbbasi PTAL?

**Comment by gino-m** [comment]
LGTM from PM perspective. @sufyanAbbasi for eng stamp.

**Review by sufyanAbbasi — APPROVED** [review]
Sorry for the delay, everything looks good to me! Well done!!

**Pull request merged**
