### PR TITLE
[Capture location task] Prompted to Correct enable location task

### LINKED ISSUE #2855: [Capture location task] Prompted to enable location on wrong task
The user is getting prompted to enable location permissions on the previous task, which in this case was a "take a photo" tasks. See start of screen recording for repro.

https://github.com/user-attachments/assets/e875aef3-f687-4cf8-beea-9ba0b4d2752a

@anandwana001 PTAL?

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2855 

@shobhitagarwal1612  PTAL?

### CODE REVIEW

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]
Instead of moving the code to CaptureLocationTaskFragment, can you do something like:

```

  override fun onResume() {
    super.onResume()
    if (isVisible) {
       // add existing code for showing permission dialog.
    }
  }
```

**Comment by anandwana001** [comment]
> Instead of moving the code to CaptureLocationTaskFragment, can you do something like:
> 
> ```
> 
>   override fun onResume() {
>     super.onResume()
>     if (isVisible) {
>        // add existing code for showing permission dialog.
>     }
>   }
> ```



it will not work, because as this fragment is a part of pagination where the code is getting executed when the index is +1.

**Comment by shobhitagarwal1612** [comment]
We care about the fragment being visible to the user. Can you try out the above code once?

**Comment by anandwana001** [comment]
> We care about the fragment being visible to the user. Can you try out the above code once?

Tried, not working

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
