### PR TITLE
#2 Gracefully handle permission denied error during signin

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Towards #1691

### Current behavior
If the user isn't in the allowlist, then the app would directly finish with a toast message. One needs to manually clear to app data in order to reset the app and attempt login again.

### Proposed behavior
A dialog is shown with 2 options : Sign out and Close app

### Other details 
Note that this PR also changes the behavior of sign out action by clearing all local tables as well.

@gino-m  PTAL?

### CODE REVIEW

**Comment by gino-m** [comment]
> Please review this PR once https://github.com/google/ground-android/pull/1808 is submitted as it is branched off of it.

Will do! Could you kindly ping once that's in so I don't forget?

**Comment by shobhitagarwal1612** [comment]
@gino-m This is now ready for a review!

**Review by gino-m — APPROVED** [review]
I made a few suggestions to the UI strings, LGTM!

**Pull request merged**
