### PR TITLE
Minor cleanups to Map impl

### PR DESCRIPTION
**Pull request by gino-m**
- [x] Use enum for `MapType` and create generic definition of map types.
- [x] Rename tile set functions, MapFragment interface
- [x] Add MOG tile set type
- [x] Start renaming "mbtiles" related classes as such to make it easy to identify them for deletion

Mbtiles impl will be deleted in next PR, please disregard changes in related classes for now.

@JSunde PTAL?

### CODE REVIEW

**Review by JSunde — APPROVED** [review]

**Review by JSunde — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
Some unit tests are still failing.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
