### PR TITLE
Renamed MutationStore -> LocalMutationStore

### PR DESCRIPTION
**Pull request by devedroy**
Towards #1590

### CODE REVIEW

**Comment by devedroy** [comment]
Screenshot (28)

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
Thanks @devedroy! I have changed the description of this PR to say "towards" instead of "fixes" as there is one more task pending before we can mark the bug as fixed.

**Comment by devedroy** [comment]
Sure.
Thanks for merging my request.

I need to see and work on the other task as some checks are failing when I try to rename it.
I will try to figure that out ASAP.

**Pull request merged**
