### PR TITLE
Cleanup out of range Data Collection fragments

### PR DESCRIPTION
**Pull request by JSunde**
Set the offScreenPageLimit of the Data Collection ViewPager2 to 1 to clean up fragments older than the last one and newer than the next one.

@gino-m PTAL?

### CODE REVIEW

**Comment by JSunde** [comment]
Towards #1146

**Comment by shobhitagarwal1612** [comment]
FYI, `/gcbrun` is no longer required. It also skips instrumentation tests.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Review by gino-m — APPROVED** [review]

**Pull request merged**
