### PR TITLE
Centers the crosshair with the points added to the map

### LINKED ISSUE #1034: [Polygon] Added points are not centered with respected to crosshair
Added points are not centered with respected to crosshair

Start polygon input type
Add first point - observe: nothing is visible.
Add second point - observe: first point, second point and connecting line is now visible. But both points are offset upwards.
Add third point - observe this being added and visible immediately, but it is also similarly offset upwards.

First point not being visible is being tracked in https://github.com/google/ground-android/issues/1033.

Expected behavior
Added point is on top of the crosshair (horizontal centered, vertical top)

Desired behavior
Added point should be centered within the crosshair.

APK used is from internal bug comment # 16

### PR DESCRIPTION
**Pull request by rachaprince**
Fixes #1034 

Centers the crosshair with the points added to the map by moving the `@+id/map_crosshairs_img` to be a sibling with `@+id/map`. 

The `android:fitsSystemWindows="true"` property in the `map_overlay` causes the map overlap and all its children to be slightly padded. So when the crosshairs were a child of `map_overlay`, the center of the crosshairs and center of the map did not align. 

Screen Shot 2021-11-17 at 2 43 40 PM

### CODE REVIEW

**Review by gino-m — DISMISSED** [review]
LGTM! Thanks for the fix!

**Comment by gino-m** [comment]
@rachaprince Build seems to be failing with:

```
/workspace/gnd/src/androidTest/java/com/google/android/gnd/AddFeatureTest.java:62: error: cannot find symbol
    onView(withId(R.id.map_crosshairs)).perform(click());
                      ^
  symbol:   variable map_crosshairs
  location: class id

> Task :gnd:compileStagingAndroidTestJavaWithJavac
/workspace/gnd/src/androidTest/java/com/google/android/gnd/AddFeatureTest.java:91: error: cannot find symbol
    onView(withId(R.id.map_crosshairs)).perform(click());
                      ^
  symbol:   variable map_crosshairs
  location: class id
```

Was something committed locally not pushed maybe?

**Comment by shobhitagarwal1612** [comment]
The id of the img has been modified. So the test needs to be updated as well

**Comment by rachaprince** [comment]
Ah yes! I didn't update the tests. 

the command `.gradlew checkCode` didn't seem to catch the error in the test. Is there another test command I could run locally?

**Comment by gino-m** [comment]
> Ah yes! I didn't update the tests.
> 
> the command `.gradlew checkCode` didn't seem to catch the error in the test. Is there another test command I could run locally?

You can run instrumented tests in `src/androidTest` on an emulator or actual device, and unit tests in `src/test` locally directly from Android Studio. Let's see what GCB reports!

**Review by gino-m — APPROVED** [review]

**Pull request merged**
