### PR TITLE
UI: Constrain task layouts to avoid overlap.

### LINKED ISSUE #2516: [Multiple choice tasks] "Other" text field obscured by keyboard
Users are unable to enter "other" text because of thiso.

Screenshot_20240625_160558

Screenshot_20240625_160700

### PR DESCRIPTION
**Pull request by scolsen**
Fixes #2516 by constraining our task container to the position of the action button dock. This ensures long multiple choice tasks aren't covered by the action buttons—the scroll region is limited to viewable area above the action button drawer.

https://github.com/user-attachments/assets/70cb99e5-1029-44f4-80c6-3a16626b9e82

### CODE REVIEW

**Review by sufyanAbbasi — APPROVED** [review]
Thank you!!!

**Review by shobhitagarwal1612 — APPROVED** [review]

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]
Some unit tests are failing. Can you please check?

**Comment by scolsen** [comment]
Weirdly enough, when I test this manually the date/time pickers are indeed visible, but now the tests are failing.

**Comment by scolsen** [comment]
Ok, failure stems from height="0dp", but this is what we want for actual rendering purposes. Any ideas how/why roboelectric/espresso fails to perform tasks on these kinds of views?

**Comment by scolsen** [comment]
Well, the gcb failed, and it's unclear to me why, but I've confirmed that the tests are working locally.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Pull request merged**
