### PR TITLE
Renamed MutationStore -> LocalMutationStore and SubmissionStore -> LocalSubmissionStore

### LINKED ISSUE #1590: Rename local store interfaces to include `Local` prefix
In `com.google.android.ground.persistence.local.stores`
* `MutationStore` -> `LocalMutationStore`
* `SubmissionStore` -> `LocalSubmissionStore`

### PR DESCRIPTION
**Pull request by devedroy**
Fixes #1590

### CODE REVIEW

**Comment by devedroy** [comment]
Hello @shobhitagarwal1612 ,
Thanks for replying.

Can you please confirm  - is this the change you expected, or does it need any other changes?
Thankyou.

**Comment by shobhitagarwal1612** [comment]
The build is failing due to code styling checks. Can you please run `checkCode` locally and ensure it is passing?

**Comment by devedroy** [comment]
Sure.
Doing that now.

**Comment by devedroy** [comment]
Hello @shobhitagarwal1612 ,
Sorry for the delay.
I tried to run gradle task `checkCode` after reverting my changes to check if the test cases pass but it was unsuccessful throwing the following exception.
image
Can you please help me to solve this problem?
Thankyou.

**Comment by shobhitagarwal1612** [comment]
I haven't seen this exception before. Have you tried cleaning the project and then trying this again?

**Comment by shobhitagarwal1612** [comment]
Also, try running the tasks run by `checkCode` individually. You can find the definition of this task in `build.gradle`

**Pull request closed without merging**
