### PR TITLE
Add CodeTriage badge

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
https://www.codetriage.com/google/ground-android

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Thanks @mmisim. Could you please merge the PR? I don't have the authorization.

**Comment by mmisim** [comment]
@shobhitagarwal1612 I actually don't either. @gino-m could you do the honors?

**Comment by gino-m** [comment]
Could you add a comment here about what this badge does for posterity and to check my own understanding?

**Comment by gino-m** [comment]
Just saw the linked page, LGTM! Thanks for adding this. Care to do the same for ground-platform?

**Comment by shobhitagarwal1612** [comment]
> Care to do the same for ground-platform?

Already sent the PR.
https://github.com/google/ground-platform/pull/360

**Pull request merged**
